### PR TITLE
Add breadcrumbs, UI tweaks

### PR DESCRIPTION
**Pull request by contolini**
This PR:
- Brings over the `/src` build script stuff.
- Adds a [breadcrumbs component](https://github.com/contolini/dash/blob/master/src/js/components/Crumbs.jsx).
- Cleans up the README and adds a coverage badge.
- Cleans up icon alignment and some other UI stuff.

@dgreisen-cfpb @imuchnik

### CODE REVIEW

**Comment by imuchnik** [comment]
Tried it locally and it seems to conflict with latest devdash changes. Let's hold off on it until after we deploy. 
Breadcrumbs look nice, but the tests are missing. 
:+1: Obligatory.

**Comment by contolini** [comment]
Abort!

**Comment by contolini** [comment]
Un-abort!

**Comment by imuchnik** [comment]
First rejected PR due to the lack of tests. A milestone of sorts! A cause for celebrations?
Grateful @contolini  is such a nice guy. :100:  :rocket: :roller_coaster: :cake: :rose: :accept: :dancers: :facepunch: :fist: :joy:

**Comment by dgreisen-cfpb** [comment]
yolo

**Comment by contolini** [comment]
yesssss

**Pull request merged**
